const list = [
    {
      id: 1,
      title: "The Monk Who Sold His Ferrari",
      author: "by Robin Sharma | 25 September 2023",
      price: 199,
      img: "https://m.media-amazon.com/images/I/61pZyTuNDYL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "The Subtle Art of Not Giving a F*ck",
      author: "by Mark Manson  | 13 September 2016",
      price: 181,
      img: "https://m.media-amazon.com/images/I/71QKQ9mwV7L._SY466_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "The 48 Laws Of Power",
      author: "by Robert Green | 3 September 2010",
      price: 259,
      img: "https://m.media-amazon.com/images/I/51HOeGpvdxL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "The Memorial Rituals Book for Healing and Hope",
      author: "by Ann Marie Puttar | 15 June 1997",
      price: 5209,
      img: "https://m.media-amazon.com/images/I/41feCQ5WzFL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Read People Like a Book",
      author: "by Patrick King | 7 December 2020",
      price: 324,
      img: "https://m.media-amazon.com/images/I/61tVw-EYRGL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Don't Sell Make them Buy",
      author: "by R. Mukund | 2 October 2022",
      price: 207,
      img: "https://m.media-amazon.com/images/I/6141lvNTSpL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "The 5 AM Club",
      author: "by Robin Sharma | 19 December 2018",
      price: 240,
      img: "https://m.media-amazon.com/images/I/618ZOX7UNNL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Breakout Trading Made Easy",
      author: "by Sunil Gurjar | 23 December 2023",
      price: 299,
      img: "https://m.media-amazon.com/images/I/61qyOqIZetL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "The Theory Of Everything",
      author: "by Stephen Hawking  | 25 September 2006",
      price: 170,
      img: "https://m.media-amazon.com/images/I/71vfo4cJCjL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Master Your Emotions",
      author: "by Thibaut Meurisse | 1 Januray 2020",
      price: 259,
      img: "https://m.media-amazon.com/images/I/711Ch3NLyaL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Reflections",
      author: "by Swami Vivekananda | 5 December 2017",
      price: 249,
      img: "https://m.media-amazon.com/images/I/71agRE4WLRL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Waiting for Shiva",
      author: "by Vikram Sampath | 28 February 2024",
      price: 453,
      img: "https://m.media-amazon.com/images/I/81NS3ASjoNL._SY466_.jpg",
      amount: 1,
    },
  ];
  
  export default list;